### ISSUE TITLE
hugoVersion not working

### ISSUE THREAD

**Issue by xoxys** [drone-plugins/drone-hugo#13]
Hi, 

i have set hugoVersion to the current release in my pipeline like this:
```yaml
    image: cbrgm/drone-hugo:latest
    hugoVersion: 0.52
```

But my site get rendered wrong, which i know happends with an older hugo version. So i tried this:
```yaml
image: alpine
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.tar.gz -q -O - | tar -xz
      - ./hugo hugo -D -E -F
```

And all works fine. So i think there might be an issue with a custom hugoVersion. Also i think it would be better to add a version output to the used hugo command to verify currently runnning version.
