### ISSUE TITLE
Version not respected, documentation needs update

### ISSUE THREAD

**Issue by maurerle** [drone-plugins/drone-hugo#25]
Hello and thanks for this plugin!
I want to report a few errors and bad documentation for newcomers.

1. Currently the links to documentation go to drone-plugins/drone-hugo but it must be http://plugins.drone.io/cbrgm/drone-hugo/

2. The documentation there states that one should set `hugo_version` as a variable but it is actually `hugoVersion` looking at your source code. So the documentation must be updated too.

3. Using hugoVersion seems to do nothing. 
Maybe you can help here:

Drone.yml:
```
kind: pipeline
name: build 

steps:
- name: build
  image: plugins/hugo
  settings:
    hugoVersion: 0.67.0
  commands:
    - hugo version
```

Drone output:
```
+ hugo version
Hugo Static Site Generator v0.58.3-4AAC02D4 linux/amd64 BuildDate: 2019-09-19T15:30:47Z
```

Thank you!

**Comment by tboerger** [comment]
1. The docs are using the right image, you are using an old version 
2. The attribute is documented totally right as the env variable gets used

**Comment by maurerle** [comment]
Could you please elaborate on that?

Using
```
  image: plugins/hugo
  settings:
    hugo_version: 0.55
  commands:
    - hugo version
```
(as stated in the docs here: http://plugins.drone.io/cbrgm/drone-hugo/)
I get 
```
+ hugo version
Hugo Static Site Generator v0.58.3-4AAC02D4 linux/amd64 BuildDate: 2019-09-19T15:30:47Z
```
So where can I find an example which sets the hugo version accordingly? And how am I using an old version? Drone is running in docker with up-to-date images of `drone/drone:1` and `drone/agent:1`.
