### ISSUE TITLE
Unknown time zone Europe/Berlin

### ISSUE THREAD

**Issue by kimdre** [drone-plugins/drone-hugo#32]
I'm trying to use the configuration in the docs, but I keep getting this error:

```
latest: Pulling from plugins/hugo
Digest: sha256:c41c437b26c2b587bd32137e3d6bba3544f92a79b4992a9b3680437ee1ec3970
Status: Image is up to date for plugins/hugo:latest
+ /tmp/401314049/852269676 check
Contains some verification checks

+ /tmp/401314049/852269676 --baseURL https://mydomain.de/
Error: invalid timeZone for language "en": unknown time zone Europe/Berlin
Total in 1 ms
exit status 255
```

Is there something I'm doing wrong?

My Config is down below.

`config.toml`:
```toml
languageCode = 'en-us'
timeZone = 'Europe/Berlin'
```

`.drone.yml`:

```yaml
kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.92.0
    pull: always
    url: https://mydomain.de/
    validate: true
    extended: true
```
