### ISSUE TITLE
Error: unknown command "check" for "hugo"

### ISSUE THREAD

**Issue by mfontani** [drone-plugins/drone-hugo#33]
Since Hugo v0.92.2 (inclusive) the `hugo check ...` command has been removed, and using this plugin with a version of hugo greater than or equal to v0.92.2 fails with:

    Error: unknown command "check" for "hugo"

... which I believe to be because the plug-in runs a "check" on the configuration file before using it.

Would it be possible to remove that check so that the builds can work with recent hugo versions?

Otherwise we're stuck with only being able to use versions up to v0.92.1 (inclusive) only :/

**Comment by xstefen** [comment]
`hugo check` is ran when `validate: true`. Although it would be preferential to have this fixed, one can set `validate: false` in the meantime.

My current mostly-functional build step:
```
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.97.0
    extended: true
    minify: true
    pull: always
    url: $URL
    validate: false
```
